---
- name: Install Dependencies on Debian
  apt:
    name:
      - build-essential 
      - unzip 
      - openssl 
      - libssl-dev 
      - apache2 
      - php 
      - libapache2-mod-php 
      - php-gd 
      - libgd-dev
    state: latest
    update_cache: yes

- name: Add nagios group
  group:
    name: nagios
    state: present

- name: Add nagcmd group
  group:
    name: nagcmd
    state: present

- name: Add nagios user
  user:
    name: nagios
    shell: /bin/bash
    comment: nagios user
    group: nagios
    password: '{{ nagios_pass }}'

- name: Adding nagios user group for External Command
  user:
    name: nagios
    group: nagcmd
    append: yes

- name: Adding www-data user group for External Command
  user:
    name: www-data
    group: nagcmd
    append: yes

- name: Creating downloads directory
  file:
    path: /downloads
    state: directory
    owner: nobody
    group: nogroup

- name: Downloading Nagios
  get_url:
    url: http://prdownloads.sourceforge.net/sourceforge/nagios/nagios-4.2.1.tar.gz
    dest: /downloads

- name: Downloading Plugins
  get_url:
    url: https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz
    dest: /downloads

- name: Extract Nagios Core
  unarchive:
    src: /downloads/nagios-4.2.1.tar.gz
    dest: /downloads
    remote_src: yes

- name: Configuring Nagios Script
  shell: ./configure --with-command-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/apache2/sites-enabled/
  args:
    chdir: /downloads/nagios-4.2.1

- name: Compiling Nagios Core
  make:
    chdir: /downloads/nagios-4.2.1
    target: all

- name: Install nagios binaries
  make:
    chdir: /downloads/nagios-4.2.1
    target: install

- name: Install init script
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-daemoninit

- name: Install config files
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-config

- name: Install commandmode
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-commandmode

- name: Install nagios webconf
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-webconf

- name: Enable Apache rewrite and CGI modules
  shell: 'a2enmod rewrite cgi'

- name: Install pip for htpasswd
  apt:
    name: python3-pip
    state: latest
    update_cache: yes

- name: Install htpasswd
  apt:
    name: python-passlib
    state: latest

- name: Add nagiosadmin account
  htpasswd:
     path: /usr/local/nagios/etc/htpasswd.users
     name: nagiosadmin
     password: '{{ nagiosadmin_pass }}'
     owner: www-data
     group: www-data

- name: Restart apache
  service:
    name: apache2
    state: reloaded

- name: Start nagios service
  shell: '/etc/init.d/nagios start'

# tasks file for roles/dmonitoring