---
- name: Install Dependencies on Centos
  yum:
    name:
      - httpd
      - gcc
      - glibc
      - glibc-common
      - gd-devel
      - perl
      - postfix
      - unzip
    state: latest
    update_cache: yes

- name: Run httpd 
  service:
    name: httpd
    state: started

- name: Add nagios group
  group:
    name: nagios
    state: present

- name: Add nagcmd group
  group:
    name: nagcmd
    state: present

- name: Add nagios user
  user:
    name: nagios
    shell: /bin/bash
    comment: nagios user
    group: nagios
    password: '{{ nagios_pass }}'

- name: Add httpd to nagios group
  user:
    name: apache
    groups: nagios
    append: yes

- name: Adding nagios user group for External Command
  user:
    name: nagios
    group: nagcmd
    append: yes

- name: Adding www-data user group for External Command
  user:
    name: www-data
    group: nagcmd
    append: yes

- name: Creating downloads directory
  file:
    path: /downloads
    state: directory

- name: Download Nagios from url
  get_url:
    url: http://prdownloads.sourceforge.net/sourceforge/nagios/nagios-4.2.1.tar.gz
    dest: /downloads

- name: Extracting Nagios Core
  unarchive:
    src: /downloads/nagios-4.2.1.tar.gz
    dest: /downloads
    remote_src: yes

- name: Creating Virtual Host Directory
  file:
    path: /etc/httpd/conf.d
    state: directory

- name: Configuring Nagios Script
  shell: ./configure --with-command-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/httpd/conf.d
  args:
    chdir: /downloads/nagios-4.2.1

- name: Compiling Nagios Core
  make:
    chdir: /downloads/nagios-4.2.1
    target: all

- name: Install nagios binaries
  make:
    chdir: /downloads/nagios-4.2.1
    target: install

- name: Install init script
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-daemoninit

- name: Install config files
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-config

- name: Install commandmode
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-commandmode

- name: Install nagios webconf
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-webconf

- name: Install exfolation
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-exfoliation

- name: Install classicui
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-classicui


- name: Install pip for htpasswd
  yum:
    name: python3-pip
    state: latest
    update_cache: yes

- name: Install htpasswd
  pip:
    name: passlib
    state: latest

- name: Add nagiosadmin account
  htpasswd:
     path: /usr/local/nagios/etc/htpasswd.users
     name: nagiosadmin
     password: '{{ nagiosadmin_pass }}'

- name: Restart Apache
  service:
    name: httpd
    state: reloaded

- name: Start Nagios service
  shell: '/etc/init.d/nagios start'

# tasks file for roles/cmonitoring